version: '3.8'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:953:953/tcp"