version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-enterprise-server:latest
    container_name: some-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: 123
      #MONGO_INITDB_DATABASE: productdb
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  mongodb-data:
