version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: some-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db  # Persistencia de datos

volumes:
  mongo_data:
