version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: some-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2006702231
      MYSQL_DATABASE: mydb
      MYSQL_USER: yas
      MYSQL_PASSWORD: 2006702231
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
