version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: some-vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root" # si se necesita que se genere automaticamente eliminar esto
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    #entrypoint: ["/bin/sh", "-c", "/vault/init-vault.sh && vault server -dev"]
    volumes:
      - ./init-vault.sh:/vault/init-vault.sh
      - vault_data:/vault/data  # Agregar volumen persistente

volumes:
  vault_data:
